name: Manual Folder Creation and Artifact Upload

on:
  workflow_dispatch:

env:
  WORKING_DIR: Python-Code  

jobs:
  folder_creation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create folders
        working-directory: ${{env.WORKING_DIR}}
        run: python Python-code.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: folder-structure
          path: ${{env.WORKING_DIR}}/MyFiles
